### ISSUE TITLE
Wheter this actually shows Turnig completeness is debated

### ISSUE THREAD

**Issue by GTP95** [tom-p-reichel/svg-is-turing-complete#1]
I haven't looked at the code, but seems that this example doesn't show SVG's ability to perform loops. AFAIK if this is true this is not enough to show Turing completeness, more info here: https://news.ycombinator.com/item?id=20980837

**Comment by laszlokorte** [comment]
If you can not construct an SVG that never halts (finishes drawing) SVG can not be turing complete.

**Comment by tom-p-reichel** [comment]
Heya, I've read through some comments and I agree that what I've made is not exactly turing complete if you want to be exceedingly accurate, so maybe that was kind of clickbaity of me. I didn't exactly expect a lot of attention-- I made this for a class project. However, what I've made shows SVG can perform arbitrary computation given the allocation of appropriate time and memory... which I think is reasonable. After all, every other computing device in existence technically has the same problems-- needing to allocate a finite portion of time and memory-- if you're picky enough, nothing is turing complete since you can always come up with a problem that exhausts the memory of any existing computing device, and we really don't practically have infinite time for computation.

**Comment by GTP95** [comment]
Of course every real computing device is subject to physical limitations, but here we're talking about a language, not a machine. For example C is a turing complete language regardless the fact that the actual computer you're running your C programs on isn't an actual implementation of a Turing machine (which is impossible to implement due the reasons you already pointed at). I'm a student too and now I'm wondering, what was the project's goal?

**Comment by boomlinde** [comment]
For a Turing machine, you can't know generally whether the machine will eventually halt or not given a program-input pair. Particularly, it is trivial to construct a program that definitely does *not* halt.

For Turing equivalent LBA, there is similarly a sort-of halting problem. You *can* determine generally whether any LBA program with any dataset will halt (because their state is finite), but for large enough bounds (say 1 GB of computer memory) it is a very costly calculation that is practically impossible. Exactly as with Turing machines, you can trivially produce a definitely non-halting program.

The code doesn't demonstrate turing completeness or even LBA. You can trivially know that *every* program halts. If this is a Turing machine by any stretch, I congratulate you on solving the halting problem so elegantly: `f(program, input) = T`

**Comment by JoJoDeveloping** [comment]
> However, what I've made shows SVG can perform arbitrary computation given the allocation of appropriate time and memory

You haven't. Your SVGs always halt after a predetermined amount of time. You cannot, for example, make an SVG that takes forever to evaluate. Your method of "copy this n times to archive n steps" results in one having to restart the computation every time it runs out of steps, which is not a valid way to show Turing completeness (because that way everything is Turing complete).

**Comment by tom-p-reichel** [comment]
I think that's what appropriate time and memory means, picking the correct amount of steps such that the task will finish. But yes, this is a driven turing machine... I've added a disclaimer to the readme.

**Comment by JoJoDeveloping** [comment]
> picking the correct amount of steps such that the task will finish
What amount of steps would that be for the machine described in here (Section 1.1)? https://arxiv.org/abs/1605.04343

**Comment by tom-p-reichel** [comment]
Lucky for us, we only have to pick the maximum possible number of steps, because going above in our case simply repeats the halted state, which makes choosing the correct number of steps trivial for this problem, just repeat infinite times. As-is, _you would have to drive the machine forever_, hence the disclaimer I already added to the readme, so this doesn't really add anything to the issue.
If you want a more interesting hypothetical, if you're on a computer with infinite memory, as turing completeness implies, just instantiate an infinite region of memory to copy-pastes of the iteration line, because you have infinite memory anyways. In that way, everything either halts (by ceasing to change) or does not halt (changes forever). This is definitely at least somewhat hand-wavy, though, and in no means a proof. Also, the renderer will always run forever in this case, but the STATE of the render won't change, so whether or not you consider that "halting" is another semantic problem, which I'd rather not get into.
I feel like this issue has already been resolved by adding a disclaimer about the capabilities of this concept, so I'm going to lock the thread. If anyone wants to discuss this further, they can e-mail me at tom.p.reichel@gmail.com .
